config/routes.rb
  Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
   devise_for :users, :controllers => { :registrations => "users/registrations" }

  devise_scope :user do
    authenticated :user do
      root 'dashboards#index', as: :authenticated_root
    end

    unauthenticated do
      root 'dashboards#home', as: :unauthenticated_root
    end
  end

  resources :orders do
    post :upload, :on => :collection
    get :user_order, :on => :member
    get :show_order, :on => :collection
    get :modify_order, on: :collection
    post :make_order, on: :collection
    get :my_orders, on: :collection
  end

  resources :dashboards do
    post :import, :on => :collection
  end

  resources :items

end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :item
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!
	require 'csv'

	def index
		# @merchant_items = Item.where("user_id =?", current_user.id)
		@sample_csv = ["code", "item", "qty"]
	    respond_to do |format|
	      format.html
	      format.csv { send_data @sample_csv.to_csv}
	      ##we can also change the downloaded CSV file name by setting filename attribute of send_data method
	      #format.csv { send_data @employees.to_csv, :filename => '<file_name>.csv' }
	    end
	end

	def home
		
	end

	def user_order
		session[:items_id] = [] if session[:items_id].blank?
		id = params[:id]
		m = id.match /(.+)-(\d+)/
		item = Item.find(m[1]).code

		session[:items_id] << params[:id]

		session[:items_id].each do |a|
			inner_id = a.match /(.+)-(\d+)/
			b = Item.find(inner_id[1]).code

			if item == b and session[:items_id].size > 2
				session[:items_id].delete_if{|i|i == a}
			end
		end

		render :nothing => true
	end

	def show_order
		@b, @c = [], []
		session[:items_id].each do |a|
			id = a.match /(.+)-(\d+)/
			@b << id[1]
			@c << id[2]
		end
		# abort @b.inspect
		@items = Item.where("id IN (?)", @b)
		# abort @items.inspect
	end


	def modify_order
		@start_date = Date.today
		@end_date = session[:delivery_date].to_date
		@b, @c, @short_items = [], [], []
		session[:items_id].each do |a|
			id = a.match /(.+)-(\d+)/
			item_code = Item.find(id[1])

			@c << id[2]

			@items = Item.where("code =? and name =? and stock >=?", item_code.code, item_code.name, id[2]).limit(3)

      		@short = @items.sort_by {|x| [x.price, x.delivery_days] }
      		@short_items << @short
		end
		@i = session[:items_id]
	end

	def upload
		session[:delivery_add] = params[:delivery_add]
		session[:postal_code] = params[:postal_code]
		session[:delivery_date] = params[:delivery_date]
		@start_date = Date.today
		@end_date = params[:delivery_date].to_date
		csv_text = File.read(params[:file].path)
	    if !csv_text.blank?
	    	csv = CSV.parse(csv_text, :headers => true)
	    	@short_items = []
	    	@qty = []
	        csv.each do |row|
	        	@items = Item.where("code =? and name =? and stock >=?", row["code"], row["item"], row["qty"]).limit(3)
	        	@qty << row["qty"]
	      		@short = @items.sort_by {|x| [x.price, x.delivery_days] }
	      		@short_items << @short
	      	end
		end
	end

	def make_order
		if params[:is_confirm]
			session[:items_id].each do |a|
				id = a.match /(.+)-(\d+)/
				item = Item.find(id[1])

				delivery_date =  Date.today + item.delivery_days
				order = Order.create!(user_id: current_user.id, merchant_id: item.user_id, item_id: item.id, item_qty: id[2], delivery_add: session[:delivery_add], postal_code: session[:postal_code], delivery_date: delivery_date, is_confirm: params[:is_confirm]  )

				@stock = item.update_attributes(stock: item.stock.to_i - id[2].to_i)

			end
			session.delete(:items_id)
			session.delete(:postal_code)
			session.delete(:delivery_add)
			session.delete(:delivery_date)
			@my_orders = Order.where("is_delivered = ?", false)
			flash[:message] = "Order placed successfully!"		
		else
			flash[:alert] = "Please confirm the order!"
			redirect_to show_order_orders_path   
		end
	end

	def my_orders
		@my_orders = Order.where("merchant_id =?", current_user.id)
	end

	def show
		flash[:alert] = "Please upload csv!"
		redirect_to dashboards_path
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_user_dashbord.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12 col-lg-6 col-sm-12 col-md-6">
			<h4 class="order-head">New Order</h4>
			<%= form_tag  upload_orders_path, multipart: true, onsubmit: "return Validate(this);" do %>
				<div class="user_order tab-pane1">
					<div class="form-group">
						<p>Delivery address</p>
						<%= text_area_tag :delivery_add, "", class: "form-control" %>
					</div>
					<div class="form-group">
						<p>Postal code</p>
						<%= text_field_tag :postal_code, "", class: "form-control" %>
					</div>
					<div class="form-group">
						<p>Delivery date</p>
						<%= text_field_tag :delivery_date, "", id: 'datepicker', class: "form-control" %>
					</div>
					<div class="nxt-btn">
						<a class="btn btn-primary btnNext pull-right" >Next</a>
					</div>
				</div>
				<div class="user_order tab-pane2">
					<h4>Search inventory</h4>
					<div class="form-group search-csv">
						<%= file_field_tag :file, :required => true %>
					</div>
					<p class="important-note"><span class="note-bold">Note* </span>User search CSV must has been this fields <span class="note-bold">code</span>, <span class="note-bold">item</span> and <span class="note-bold">qty</span>.</p>
					<div class="nxt-prev">
						<a class="btn btn-primary btnPrevious pull-right" >Back</a>
					</div>
					<div class="search-btn">
						<%= submit_tag "Search Inventory", class: "btn btn-primary pull-left" %>
					</div>
					<div class="sample-csv">
						<%= link_to "Download Sample CSV", orders_path(format: "csv"), class: "btn btn-primary smpl-csv" %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
  	$('#datepicker').datepicker({ dateFormat: 'dd-mm-yy' });
	$('.btnNext').click(function(){
      $('.tab-pane1').css('display', 'none');
      $('.tab-pane2').css('display', 'block');
	});
	$('.btnPrevious').click(function(){
      $('.tab-pane1').css('display', 'block');
      $('.tab-pane2').css('display', 'none');
	});
  });
</script>

<style type="text/css">
	.tab-pane2 {
		display: none;
	}
</style>

app/views/orders/index.html.erb
<div>
	<%# if current_user.user_type == true %>
        <%#= render :partial => 'merchant_dashbord' %>
	<%# else %>
        <%= render :partial => 'user_dashbord' %>
	<%# end %>
</div>

<script type="text/javascript">
var _validFileExtensions = [".csv"];    
function Validate(oForm) {
    var arrInputs = oForm.getElementsByTagName("input");
    for (var i = 0; i < arrInputs.length; i++) {
        var oInput = arrInputs[i];
        if (oInput.type == "file") {
            var sFileName = oInput.value;
            if (sFileName.length > 0) {
                var blnValid = false;
                for (var j = 0; j < _validFileExtensions.length; j++) {
                    var sCurExtension = _validFileExtensions[j];
                    if (sFileName.substr(sFileName.length - sCurExtension.length, sCurExtension.length).toLowerCase() == sCurExtension.toLowerCase()) {
                        blnValid = true;
                        break;
                    }
                }
                
                if (!blnValid) {
                    alert("Sorry, file is invalid, allowed extensions are: " + _validFileExtensions.join(", "));
                    return false;
                }
            }
        }
    }
  
    return true;
}
</script>

app/views/orders/make_order.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-8 col-lg-offset-2 main-class">
			<h3 class="heading">Done!</h3>
			<div class="row main">
				<div class="col-lg-6">
					<h4>Order Number:- <span><%= rand.to_s[2..11] %></span></h4>
				</div>
				<div class="col-lg-6">
					<h4>Date:- <span><%= Date.today %></span></h4>
				</div>
			</div>
			<div class="row main">
				<div class="col-lg-12">
					<div class="table-responsive">
			            <table class="table table-hover receipt">
			                <thead>
			                    <tr>
			                        <th>Item Code</th>
			                        <th>Item Name</th>
			                        <th>Item Qty</th>
			                        <th>Item Price</th>
			                        <th>Delivery Date</th>
			                        <th>Total</th>
			                    </tr>
			                </thead>

			                <tbody>
			                	<% @total = [] %>
	                            <% @my_orders.each do |h| %>
		                            <tr>
		                                <td><%= h.item.code %></td>
		                                <td><%= h.item.name %></td>
		                                <td><%= h.item_qty %></td>
		                                <td> $ <%= h.item.price %></td>
		                                <td><%= h.delivery_date %></td>
		                                <td> $ <%= h.item_qty * h.item.price %></td>
		                                <% @total << h.item_qty * h.item.price  %>
		                            </tr>
		                    	<% end %>
			                </tbody>
			            </table>
	        		</div>
				</div>
			</div>
			<div class="row main">
				<div class="col-lg-12">
					<div class="table-responsive">
						<% @final_total = @total.inject(0){|sum,x| sum + x } %>
						<table class="table-class">
							<tr class="spaceUnder">
								<td>Total</td>
								<td></td>
								<td></td>
								<td>$ <%= @final_total %></td>
							</tr>
							<tr>
								<td>+ GST</td>
								<td></td>
								<td></td>
								<td> 12% </td>
							</tr>
						</table>
					</div>	
				</div>
			</div>
			<div class="row main">
				<div class="col-lg-12">
					<div class="table-responsive">
						<table class="table-class">
							<tr class="spaceUnder">
								<td>Paid amount</td>
								<td></td>
								<td></td>
								<% @a = @final_total / 100 %>
								<% @b = (12 * @a.to_f) %>
								<td>$ <%= @final_total + @b %></td>
							</tr>
						</table>
					</div>
				</div>
			</div>
			<!-- <div class="row main">
				<div class="col-lg-3">
					<h4>Delivery date:-</h4>
				</div>
				<div class="col-lg-9">
					<h4 class="date">11/11/2017</h4>
				</div>
			</div> -->
			<div class="row main">
				<div class="col-lg-3">
					<h4>Delivery address:-</h4>
				</div>
				<div class="col-lg-9">
					<h4 class="date"><%= @my_orders.first.delivery_add %></h4>
				</div>
			</div>
			<div class="row main">
				<div class="col-lg-6">
					<button type="button" class="btn btn-success">Print</button>
				</div>
				<div class="col-lg-6">
					<%= link_to "  Log out", destroy_user_session_path, :method => :delete, class:"btn btn-danger" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/orders/modify_order.html.erb
<div class="container">
    <div class="row">
        <h2 class="main-heading">Searched Inventories</h2>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Item Code</th>
                        <th>Item Name</th>
                        <th>Item Specification</th>
                        <th>Item Price</th>
                        <th>Item Delivery Days</th>
                        <th>Qty</th>
                        <th>Item Delivery Date</th>
                        <th>Make Order</th>
                    </tr>
                </thead>

                <tbody>
                        <% i = 0 %>
                        <% @short_items.each do |h| %>

                        <% h.each do |s| %>
                            <tr id="element" class="item_<%= s.id %>">
                                <td><%= s.code %></td>
                                <td><%= s.name %></td>
                                <td><%= s.specification %></td>
                                <td><%= s.price %></td>
                                <td><%= s.delivery_days %></td>
                                <td><%= @c[i] %></td>
                                <td><%= @start_date + s.delivery_days %></td>
                                <td>
                                    <label><input type="radio" class="user_item" id="item_<%= s.id %>" name="<%= s.code %>" data-id="<%= s.id %>-<%= @c[i]%>" data-val="<%= @c[i] %>"></label>
                                </td>
                            </tr>
                        <% end %>
                            <tr>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                            </tr>
                        <% i += 1 %>
                    <% end %>
                </tbody>
                <div id="result"></div>
            </table>
        </div>
  </div>
  <div class="row">
    <div class="col-lg-12 nxt-btn">
        <!-- <button type="button" id="nxt_btn">Next</button> -->
        <%= link_to "Next", show_order_orders_path, class: 'btn btn-primary'%>
    </div>
  </div>
</div>


<% @z = [] %>
<% @l = [] %>
<% @i.each do |m|%>
    <% id = m.match /(.+)-(\d+)/ %>
  <% @z << id[1].to_i %>
  <% @l << id[2].to_i  %>
<% end %>
<% @size = @z.size %>
<%= hidden_field_tag :item_id , @z %>

<script type="text/javascript">

    $(document).ready(function(){
        var a = $("#item_id").val();
        var n = "<%= @l %>";
        var size = "<%= @size %>"
        var res = a.split(" ");
        for(i=0;i<=size-1;i++){
            // alert(a[i])
            $("#item_"+res[i]).prop("checked", true);
            $(".item_"+res[i]).css('background-color', 'azure');
            // $("#item_10").prop("checked", true);
        }

        $(".user_item").click(function(){
            var dclass = $(this).closest('tr').next('tr').attr("class");
            var pclass = $(this).closest('tr').prev('tr').attr("class");
            var ddclass = $(this).closest('tr').next('tr').next('tr').attr("class");
            var ppclass = $(this).closest('tr').prev('tr').prev('tr').attr("class");
            $('.'+ dclass).css('background-color', 'white');
            $('.'+ pclass).css('background-color', 'white');
            $('.'+ ddclass).css('background-color', 'white');
            $('.'+ ppclass).css('background-color', 'white');
            var a = $(this).attr("id");
            $('.'+ a).css('background-color', 'azure');
            var item_id = $(this).attr("data-id");
            $.ajax({
                type: "get",
                url: '/orders/' + item_id + '/user_order',
                success:function(data) {
                    // alert(data);
                }
            });
        });
    });
</script>

app/views/orders/my_orders.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div class="user-orders">
				<h2 class="main-heading">My Orders</h2>
				<% if @my_orders.blank? %>
					<p class="no-slug">You have no orders.</p>
				<% else %>
					<div class="table-responsive">
			            <table class="table table-hover">
			                <thead>
			                    <tr>
			                        <th>Item Code</th>
			                        <th>Item Name</th>
			                        <th>Item Specification</th>
			                        <th>Item Price</th>
			                        <th>Qty</th>
			                        <th>Item Delivery Date</th>
			                        <th>Item address</th>
			                    </tr>
			                </thead>

			                <tbody>
		                        <% @my_orders.each do |s| %>
		                            <tr id="element">
		                                <td><%= s.item.code %></td>
		                                <td><%= s.item.name %></td>
		                                <td><%= s.item.specification %></td>
		                                <td><%= s.item.price %></td>
		                                <td><%= s.item_qty %></td>
		                                <td><%= s.delivery_date %></td>
		                                <td><%= s.delivery_add %></td>
		                            </tr>
			                    <% end %>
			                </tbody>
			            </table>
			        </div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/orders/show_order.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div class="merch-item">
				<h2 class="main-heading">Confirm order</h2>
				<div class="table-responsive">
				<!-- <input type="checkbox" name="vehicle" value="Bike" class="Confirm-order"> 	Confirm order &nbsp;&nbsp;&nbsp;&nbsp; -->
		            <table class="table table-hover">
		                <thead>
		                    <tr>
		                        <th>Item Code</th>
		                        <th>Item Name</th>
		                        <th>Item Qty</th>
		                        <th>Item Price</th>
		                        <th>Sub Total</th>
		                    </tr>
		                </thead>

		                <tbody>
		                	<% i = 0 %>
		                    <% @items.each do |h| %>
	                            <tr>
	                                <td><%= h.code %></td>
	                                <td><%= h.name %></td>
	                                <td><%= @c[i] %></td>
	                                <td><%= h.price %></td>
	                                <td><%= @c[i].to_i * h.price %></td>
	                            </tr>
	                          	<% i += 1 %>
		                    <% end %>
		                </tbody>
		            </table>
		        </div>
			</div>
			<div class="modify-sec">
				<div class="modify-order pull-right">
					<%= link_to "Modify", modify_order_orders_path(type: 'm'), class:"btn btn-primary"%>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12 pay-section">
			<div class="pay-btn">
				<%= form_tag make_order_orders_path do %>
					<%= check_box_tag :is_confirm %>  <span class="confirm">Confirm order</span><br/><br/>
					<%= submit_tag "Pay", class: "btn btn-primary submit-order" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/orders/upload.html.erb
<div class="container">
    <div class="row">
        <h2 class="main-heading">Searched Inventories</h2>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Item Code</th>
                        <th>Item Name</th>
                        <th>Item Specification</th>
                        <th>Item Price</th>
                        <th>Item Delivery Days</th>
                        <th>Qty</th>
                        <th>Item Delivery Date</th>
                        <th>Make Order</th>
                    </tr>
                </thead>

                <tbody>
                        <% i = 0 %>
                        <% @short_items.each do |h| %>
                        <% h.each do |s| %>
                            <tr id="element" class="item_<%= s.id %>">
                                <td><%= s.code %></td>
                                <td><%= s.name %></td>
                                <td><%= s.specification %></td>
                                <td><%= s.price %></td>
                                <td><%= s.delivery_days %></td>
                                <td><%= @qty[i] %></td>
                                <td><%= @start_date + s.delivery_days %></td>
                                <td>
                                    <label><input type="radio" class="user_item" id="item_<%= s.id %>" name="<%= s.code %>" data-id="<%= s.id %>-<%= @qty[i]%>" data-val="<%= @qty[i] %>"></label>
                                </td>
                            </tr>
                        <% end %>
                            <tr>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr></tr>
                        <% i += 1 %>
                    <% end %>
                </tbody>
                <div id="result"></div>
            </table>
        </div>
  </div>
  <div class="row">
    <div class="col-lg-12 nxt-btn">
        <%= link_to "Next", show_order_orders_path, class: 'btn btn-primary'%>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){

        // $(".user_item").click(function(){
        //     $('.user_item').removeClass("checked");
        //     $(this).addClass("active");
        // });
        $(".user_item").click(function(){
            var dclass = $(this).closest('tr').next('tr').attr("class");
            var pclass = $(this).closest('tr').prev('tr').attr("class");
            var ddclass = $(this).closest('tr').next('tr').next('tr').attr("class");
            var ppclass = $(this).closest('tr').prev('tr').prev('tr').attr("class");
            $('.'+ dclass).css('background-color', 'white');
            $('.'+ pclass).css('background-color', 'white');
            $('.'+ ddclass).css('background-color', 'white');
            $('.'+ ppclass).css('background-color', 'white');
            var a = $(this).attr("id");
            $('.'+ a).css('background-color', 'azure');
            var item_id = $(this).attr("data-id");
            $.ajax({
                type: "get",
                url: '/orders/' + item_id + '/user_order',
                success:function(data) {
                    // alert(data);
                }
            });
        });
    });
</script>

app/views/orders/upload_inventory.html.erb
<%#= form_tag  import_dashboards_path, multipart: true do %>
	<%#= file_field_tag :file %>
	<%#= submit_tag "Import CSV" %>
<%# end %> 