config/routes.rb
  Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
   devise_for :users, :controllers => { :registrations => "users/registrations" }

  devise_scope :user do
    authenticated :user do
      root 'dashboards#index', as: :authenticated_root
    end

    unauthenticated do
      root 'dashboards#home', as: :unauthenticated_root
    end
  end

  resources :orders do
    post :upload, :on => :collection
    get :user_order, :on => :member
    get :show_order, :on => :collection
    get :modify_order, on: :collection
    post :make_order, on: :collection
    get :my_orders, on: :collection
  end

  resources :dashboards do
    post :import, :on => :collection
  end

  resources :items

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	before_action :authenticate_user!
	require 'csv'

	def index
		@user_orders = Order.where("user_id =?", current_user.id)
		@merchant_items = Item.where("user_id =?", current_user.id)
	end

	def import
		csv_text = File.read(params[:file].path)
	    if !csv_text.blank?
	    	csv = CSV.parse(csv_text, :headers => true)
	        csv.each do |row|
	        	Item.create!(user_id: current_user.id, code: row["code"], name: row["name"], specification: row["specification"], price: row["price"], stock: row["stock"], delivery_days: row["delivery_days"])
	      	end
		end
		flash[:success] = "CSV has been uploaded!!"
		redirect_to request.referer
	end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_merchant_dashbord.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-9">
			<div class="user-orders">
				<h2 class="main-heading">Yours Inventory list!</h2>
				<div class="col-xs-9 col-lg-9 col-sm-9 col-md-9">
					<div class="merch-item">
						<div class="table-responsive">
				            <table class="table table-hover">
				                <thead>
				                    <tr>
				                        <th>Item Code</th>
				                        <th>Item Name</th>
				                        <th>Item Specification</th>
				                        <th>Item Price</th>
				                        <th>Item Stock</th>
				                        <th>Item Delivery Days</th>
				                    </tr>
				                </thead>

				                <tbody>
				                    <% @merchant_items.each do |h| %>
			                            <tr>
			                                <td><%= h.code %></td>
			                                <td><%= h.name %></td>
			                                <td><%= h.specification %></td>
			                                <td><%= h.price %></td>
			                                <td><%= h.stock %></td>
			                                <td><%= h.delivery_days %></td>
			                            </tr>
				                    <% end %>
				                </tbody>
				            </table>
				        </div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-3 new-orders">
			<div class="upld-inventory">
				<h4>Upload your inventory</h4>
				<%= form_tag  import_dashboards_path, multipart: true, onsubmit: "return Validate(this);" do %>
					<%= file_field_tag :file, :required => true %></br>
					<%= submit_tag "Upload Inventory", class: "btn btn-primary" %>
				<% end %>
			</div>
			<div class="order-list">
				<h4>My Order</h4>
				<%= link_to "Your Orders", my_orders_orders_path, class:"btn btn-primary" %>
			</div>
			<div class="order-list">
				<h4>Edit profile</h4>
				<%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-primary' %>
			</div>
		</div>
	</div>
</div>

app/views/dashboards/_user_dashbord.html.erb
<div class="container">
	<div class="row">
		<div class="make-order">
			<%= link_to 'New Order', orders_path, class: 'btn btn-primary new-order' %>
			<%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-primary' %>
		</div>
		<div class="col-lg-12">
			<div class="user-orders">
				<h2 class="main-heading">Yours Orders</h2>
				<% if @user_orders.blank? %>
					<p class="no-slug">You have no orders.</p>
				<% else %>
					<div class="table-responsive">
			            <table class="table table-hover">
			                <thead>
			                    <tr>
			                        <th>Item Code</th>
			                        <th>Item Name</th>
			                        <th>Item Specification</th>
			                        <th>Item Price</th>
			                        <th>Qty</th>
			                        <th>Item Delivery Date</th>
			                    </tr>
			                </thead>

			                <tbody>
		                        <% @user_orders.each do |s| %>
		                            <tr id="element">
		                                <td><%= s.item.code %></td>
		                                <td><%= s.item.name %></td>
		                                <td><%= s.item.specification %></td>
		                                <td><%= s.item.price %></td>
		                                <td><%= s.item_qty %></td>
		                                <td><%= s.delivery_date %></td>
		                            </tr>
			                    <% end %>
			                </tbody>
			            </table>
			        </div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/dashboards/home.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12 col-lg-12 col-sm-12 col-md-12">
			<div class="cover-photo">
				<img src="inventory.jpg" alt="Smiley face" height="100%" width="100%">
			</div>
		</div>
	</div>
</div>

app/views/dashboards/index.html.erb
<div>
	<% if current_user.user_type == true %>
        <%= render :partial => 'merchant_dashbord' %>
	<% else %>
        <%= render :partial => 'user_dashbord' %>
	<% end %>
</div>

<script type="text/javascript">
var _validFileExtensions = [".csv"];    
function Validate(oForm) {
    var arrInputs = oForm.getElementsByTagName("input");
    for (var i = 0; i < arrInputs.length; i++) {
        var oInput = arrInputs[i];
        if (oInput.type == "file") {
            var sFileName = oInput.value;
            if (sFileName.length > 0) {
                var blnValid = false;
                for (var j = 0; j < _validFileExtensions.length; j++) {
                    var sCurExtension = _validFileExtensions[j];
                    if (sFileName.substr(sFileName.length - sCurExtension.length, sCurExtension.length).toLowerCase() == sCurExtension.toLowerCase()) {
                        blnValid = true;
                        break;
                    }
                }
                
                if (!blnValid) {
                    alert("Sorry, file is invalid, allowed extensions are: " + _validFileExtensions.join(", "));
                    return false;
                }
            }
        }
    }
  
    return true;
}
</script>

app/views/dashboards/upload.html.erb
<div class="container">
    <div class="row">
        <h2>Searched Inventories</h2>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Item Code</th>
                        <th>Item Name</th>
                        <th>Item Specification</th>
                        <th>Item Price</th>
                        <th>Item Delivery Date</th>
                    </tr>
                </thead>

                <tbody>
                    <% @search_items.each do |h| %>
                        <% h.each do |s| %>
                            <tr>
                                <td><%= s.code %></td>
                                <td><%= s.name %></td>
                                <td><%= s.specification %></td>
                                <td><%= s.price %></td>
                                <td><%= s.delivery_days %></td>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
        </div>
  </div>
  <%#= link_to 'New Account', new_account_path, class:"btn btn-primary" %>
</div>

app/views/dashboards/upload_inventory.html.erb
<%#= form_tag  import_dashboards_path, multipart: true do %>
	<%#= file_field_tag :file %>
	<%#= submit_tag "Import CSV" %>
<%# end %> 