config/routes.rb
  Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
   devise_for :users, :controllers => { :registrations => "users/registrations" }

  devise_scope :user do
    authenticated :user do
      root 'dashboards#index', as: :authenticated_root
    end

    unauthenticated do
      root 'dashboards#home', as: :unauthenticated_root
    end
  end

  resources :orders do
    post :upload, :on => :collection
    get :user_order, :on => :member
    get :show_order, :on => :collection
    get :modify_order, on: :collection
    post :make_order, on: :collection
    get :my_orders, on: :collection
  end

  resources :dashboards do
    post :import, :on => :collection
  end

  resources :items

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shop" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <a class="navbar-brand" href="#">Shop</a> -->
        <%= link_to image_tag("logo.png", :class => "img_preview"), "/", class: "navbar-brand logo" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if admin_signed_in? %>
              <li><%= link_to "  Sign out", destroy_admin_session_path, :method => :delete, class:"fa fa-sign-out" %></li>
            <% else %>
              <li><%= link_to "  Sign In", new_admin_session_path, class:"fa fa-sign-in" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
        <div class="sticky-footer">
          <%= yield %>
        </div>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
  </body>
  <footer class="footer-distributed">
    <div class="footer-left">
      <h3>Company<span>logo</span></h3>
      <p class="footer-links">
        <a href="#">Home</a>
        ·
        <a href="#">About</a>
        ·
        <a href="#">Faq</a>
        ·
        <a href="#">Contact</a>
      </p>
      <p class="footer-company-name">ComInfo &copy; 2017</p>
    </div>
    <div class="footer-center">
      <div>
        <i class="fa fa-map-marker"></i>
        <p><span>207, Sahajanand Flate</span> xxxx, xxxxx</p>
      </div>

      <div>
        <i class="fa fa-phone"></i>
        <p>+91 555 123456</p>
      </div>

      <div>
        <i class="fa fa-envelope"></i>
        <p><a href="mailto:support@company.com">support@company.com</a></p>
      </div>

    </div>
    <div class="footer-right">
      <p class="footer-company-about">
        <span>About the company</span>
        Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet.
      </p>
      <div class="footer-icons">
        <%#= social_share_button_tag("my company") %>
        <!-- <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
        <a href="#"><i class="fa fa-github"></i></a> -->
      </div>
    </div>
  </footer>
<script type="text/javascript">
  $(document).ready(function() {
    function setHeight() {
      windowHeight = $(window).innerHeight();
      $('.sticky-footer').css('min-height', windowHeight-278);
    };
    setHeight();
    
    $(window).resize(function() {
      setHeight();
    });
  });
</script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shop" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <a class="navbar-brand" href="#">Shop</a> -->
        <%= link_to image_tag("logo.png", :class => "img_preview"), "/", class: "navbar-brand logo" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <% if current_user.user_type == true %>
                <li><%= link_to " (Merchant) #{current_user.name}", "/", class:"fa fa-user" %></li>
              <% else %>
                <li><%= link_to " (Buyer) #{current_user.name}", "/", class:"fa fa-user" %></li>
              <% end %>
              <li><%= link_to "  Sign out", destroy_user_session_path, :method => :delete, class:"fa fa-sign-out" %></li>
            <% else %>
              <li><%= link_to "  Sign In", new_user_session_path, class:"fa fa-sign-in" %> </li>
              <li><%= link_to "  Sign up", new_user_registration_path, class:"fa fa-sign-up" %> </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
        <div class="sticky-footer">
          <%= yield %>
        </div>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
  </body>
  <footer class="footer-distributed">
    <div class="footer-left">
      <h3>Company<span>logo</span></h3>
      <p class="footer-links">
        <a href="#">Home</a>
        ·
        <a href="#">About</a>
        ·
        <a href="#">Faq</a>
        ·
        <a href="#">Contact</a>
      </p>
      <p class="footer-company-name">ComInfo &copy; 2017</p>
    </div>
    <div class="footer-center">
      <div>
        <i class="fa fa-map-marker"></i>
        <p><span>207, Sahajanand Flate</span> xxxx, xxxxx</p>
      </div>

      <div>
        <i class="fa fa-phone"></i>
        <p>+91 555 123456</p>
      </div>

      <div>
        <i class="fa fa-envelope"></i>
        <p><a href="mailto:support@company.com">support@company.com</a></p>
      </div>

    </div>
    <div class="footer-right">
      <p class="footer-company-about">
        <span>About the company</span>
        Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet.
      </p>
      <div class="footer-icons">
        <%#= social_share_button_tag("my company") %>
        <!-- <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
        <a href="#"><i class="fa fa-github"></i></a> -->
      </div>
    </div>
  </footer>
<script type="text/javascript">
  $(document).ready(function() {
    function setHeight() {
      windowHeight = $(window).innerHeight();
      $('.sticky-footer').css('min-height', windowHeight-278);
    };
    setHeight();
    
    $(window).resize(function() {
      setHeight();
    });
  });
</script>
</html>